"""
env-sentry
A tiny, zero-dependency CLI that keeps your .env setup safe and sane.

Commands:
    env-sentry init    Scaffold .env.example and make sure .env is git-ignored
    env-sentry check   Compare .env against .env.example and flag drift
    env-sentry sync    Regenerate .env.example from .env (values redacted)
    env-sentry scan    Walk the repo looking for hardcoded secrets
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

VERSION = "0.1.0"

# ----------------------------------------------------------------------
# .env parsing helpers
# ----------------------------------------------------------------------

_KV_RE = re.compile(r"""^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$""")


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a .env-style file into a dict of key -> raw value string."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(errors="ignore").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = _KV_RE.match(line)
        if not match:
            continue
        key, val = match.group(1), match.group(2).strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ("'", '"'):
            val = val[1:-1]
        values[key] = val
    return values


# ----------------------------------------------------------------------
# check / sync / init
# ----------------------------------------------------------------------

def cmd_check(args: argparse.Namespace) -> int:
    env_path = Path(args.env)
    example_path = Path(args.example)

    env_vars = parse_env_file(env_path)
    example_vars = parse_env_file(example_path)

    exit_code = 0

    if not env_path.exists():
        print(f"⚠️  {env_path} not found (nothing to compare against).")
    if not example_path.exists():
        print(f"⚠️  {example_path} not found. Run `env-sentry sync` to create it.")
        exit_code = 1

    missing_in_example = sorted(set(env_vars) - set(example_vars))
    missing_in_env = sorted(set(example_vars) - set(env_vars))

    if missing_in_example:
        exit_code = 1
        print(f"\n❌ Keys in {env_path} but missing from {example_path}:")
        for key in missing_in_example:
            print(f"   - {key}")

    if missing_in_env:
        print(f"\nℹ️  Keys in {example_path} but not set in {env_path}:")
        for key in missing_in_env:
            print(f"   - {key}")

    # Warn if .env.example contains what looks like a real secret
    suspicious = [k for k, v in example_vars.items() if looks_like_secret(k, v)]
    if suspicious:
        exit_code = 1
        print(f"\n🚨 {example_path} may contain REAL secret values, not placeholders:")
        for key in suspicious:
            print(f"   - {key}")
        print("   Replace these with placeholders like `your_api_key_here` before committing.")

    # Warn if .env is not gitignored
    if not is_gitignored(".env"):
        exit_code = 1
        print(f"\n🚨 '.env' does not appear to be listed in .gitignore!")
        print("   Anyone who commits will leak real secrets. Run `env-sentry init` to fix this.")

    if exit_code == 0:
        print("✅ .env and .env.example are in sync. .env is git-ignored. Looking good.")

    return exit_code


def cmd_sync(args: argparse.Namespace) -> int:
    env_path = Path(args.env)
    example_path = Path(args.example)

    if not env_path.exists():
        print(f"❌ {env_path} not found, nothing to sync from.")
        return 1

    env_vars = parse_env_file(env_path)
    lines = ["# Auto-generated by env-sentry — fill in real values in your own .env\n"]
    for key in env_vars:
        lines.append(f"{key}=your_{key.lower()}_here\n")

    example_path.write_text("".join(lines))
    print(f"✅ Wrote {len(env_vars)} placeholder keys to {example_path}")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    exit_code = 0
    example_path = Path(args.example)
    if not example_path.exists():
        example_path.write_text("# Copy this file to .env and fill in real values\n")
        print(f"✅ Created {example_path}")
    else:
        print(f"ℹ️  {example_path} already exists, leaving it alone.")

    gitignore_path = Path(".gitignore")
    if not is_gitignored(".env"):
        with gitignore_path.open("a") as f:
            f.write("\n.env\n")
        print("✅ Added '.env' to .gitignore")
    else:
        print("ℹ️  '.env' is already git-ignored.")

    return exit_code


def is_gitignored(name: str) -> bool:
    gitignore_path = Path(".gitignore")
    if not gitignore_path.exists():
        return False
    patterns = [p.strip() for p in gitignore_path.read_text().splitlines()]
    return name in patterns or f"/{name}" in patterns or "*.env" in patterns


# ----------------------------------------------------------------------
# secret detection
# ----------------------------------------------------------------------

SECRET_KEY_HINTS = re.compile(
    r"(secret|token|api[_-]?key|password|passwd|access[_-]?key|private[_-]?key|"
    r"auth|credential|client[_-]?secret)",
    re.IGNORECASE,
)

PLACEHOLDER_RE = re.compile(
    r"^(your|my|example|placeholder|xxx+|changeme|todo|<.*>|\$\{.*\}|test|fake|dummy)",
    re.IGNORECASE,
)

# Well-known secret formats worth flagging outright.
KNOWN_PATTERNS = {
    "AWS Access Key": re.compile(r"AKIA[0-9A-Z]{16}"),
    "GitHub Token": re.compile(r"gh[pousr]_[A-Za-z0-9]{36,}"),
    "Slack Token": re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"),
    "Stripe Key": re.compile(r"sk_live_[A-Za-z0-9]{20,}"),
    "Private Key Block": re.compile(r"-----BEGIN (RSA|EC|OPENSSH|DSA|PGP)? ?PRIVATE KEY-----"),
    "Generic JWT": re.compile(r"eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"),
}

DEFAULT_IGNORE_DIRS = {
    ".git", "node_modules", "venv", ".venv", "__pycache__", "dist", "build",
    ".mypy_cache", ".pytest_cache", "target", ".next", ".tox", "vendor",
}

SCANNABLE_EXTENSIONS = {
    ".py", ".js", ".ts", ".jsx", ".tsx", ".env", ".yml", ".yaml", ".json",
    ".toml", ".ini", ".cfg", ".sh", ".rb", ".go", ".java", ".php", ".txt",
    ".properties", ".conf",
}


def looks_like_secret(key: str, value: str) -> bool:
    if not value or PLACEHOLDER_RE.match(value):
        return False
    if len(value) < 12:
        return False
    if not SECRET_KEY_HINTS.search(key):
        return False
    return True


def scan_line(line: str) -> list[str]:
    findings = []
    for name, pattern in KNOWN_PATTERNS.items():
        if pattern.search(line):
            findings.append(name)
    match = _KV_RE.match(line)
    if match:
        key, val = match.group(1), match.group(2).strip().strip("'\"")
        if looks_like_secret(key, val):
            findings.append(f"Suspicious value for '{key}'")
    return findings


def cmd_scan(args: argparse.Namespace) -> int:
    root = Path(args.path)
    total_findings = 0

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in DEFAULT_IGNORE_DIRS and not d.startswith(".git")]
        for filename in filenames:
            file_path = Path(dirpath) / filename
            if file_path.suffix not in SCANNABLE_EXTENSIONS and filename != ".env":
                continue
            try:
                lines = file_path.read_text(errors="ignore").splitlines()
            except (UnicodeDecodeError, OSError):
                continue
            for lineno, line in enumerate(lines, start=1):
                findings = scan_line(line)
                for finding in findings:
                    total_findings += 1
                    print(f"{file_path}:{lineno}  {finding}")

    if total_findings == 0:
        print("✅ No obvious hardcoded secrets found.")
        return 0
    else:
        print(f"\n🚨 {total_findings} potential secret(s) found. Review before committing/pushing.")
        return 1


# ----------------------------------------------------------------------
# entrypoint
# ----------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="env-sentry",
        description="Keep your .env setup safe and in sync. Zero dependencies.",
    )
    parser.add_argument("--version", action="version", version=f"env-sentry {VERSION}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    p_init = subparsers.add_parser(
        "init",
        help="Scaffold .env.example and git-ignore .env",
        description="Create .env.example if it doesn't exist yet, and make sure "
        "'.env' is listed in .gitignore so real secrets never get committed.",
    )
    p_init.add_argument(
        "--example", default=".env.example",
        help="Path to the example file to create (default: .env.example)",
    )
    p_init.set_defaults(func=cmd_init)

    p_check = subparsers.add_parser(
        "check",
        help="Compare .env against .env.example",
        description="Diff .env against .env.example, flag any real secret values "
        "left in the example file, and confirm .env is git-ignored. "
        "Exits non-zero if anything looks wrong (safe to use in CI).",
    )
    p_check.add_argument(
        "--env", default=".env",
        help="Path to your real env file (default: .env)",
    )
    p_check.add_argument(
        "--example", default=".env.example",
        help="Path to the example/template file to compare against (default: .env.example)",
    )
    p_check.set_defaults(func=cmd_check)

    p_sync = subparsers.add_parser(
        "sync",
        help="Regenerate .env.example from .env (values redacted)",
        description="Rewrite .env.example using the keys from .env, but with every "
        "value replaced by a placeholder — your real secrets are never copied.",
    )
    p_sync.add_argument(
        "--env", default=".env",
        help="Path to your real env file to read keys from (default: .env)",
    )
    p_sync.add_argument(
        "--example", default=".env.example",
        help="Path to the example file to write (default: .env.example)",
    )
    p_sync.set_defaults(func=cmd_sync)

    p_scan = subparsers.add_parser(
        "scan",
        help="Scan the repo for hardcoded secrets",
        description="Recursively scan source files for AWS/GitHub/Slack/Stripe keys, "
        "private key blocks, JWTs, and suspicious KEY=value pairs. "
        "Exits non-zero if anything is found (safe to use as a pre-commit hook).",
    )
    p_scan.add_argument(
        "path", nargs="?", default=".",
        help="Directory to scan (default: current directory)",
    )
    p_scan.set_defaults(func=cmd_scan)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
